install.packages(raster)
diftime("2018-12-24",Sys.Date(), units="days")
install.packages(diftime)
difftime("2018-12-24", Sys.Date(), units="days")
install.packages("raster")
library(raster)
germany<- getData("GADM", country='DEU', level=2)
plot (germany)
prec<- getData("worldclim", var="prec", res=.5, lon=10,lat=51)
plot(prec)
prec_ger1<-crop(prec, germany)
spplot(prec_ger1)
prec_ger2<- mask(prec_ger1, germany)
spplot(prec_ger2)
prec_avg<-cellStats(prec_ger2, stat="mean")

switzerland<- getData("GADM", country="CHE", level=2)
plot(switzerland)
prec<- getData("worldclim", var="prec", res=.5,lon=10, lat=51)
plot(prec)
prec_swit1<-crop(prec, switzerland)
spplot(prec_swit1)
prec_swit2<-mask(prec_swit1, switzerland)
spplot(prec_swit2)
prec_avg<- cellStats(prec_swit2, stat="mean")
